name: 'qualtrics'
version: '0.2.0'
config-version: 2
require-dbt-version: [">=1.3.0", "<2.0.0"] 

models:
  qualtrics:
    +tags:
      - "qualtrics"
      - "fivetran_package"
    +schema: qualtrics
    +materialized: table
    intermediate:
      +materialized: ephemeral
      +schema: int_qualtrics

vars:
  qualtrics:
    user: "{{ ref('stg_qualtrics__user') }}"
    survey: "{{ ref('stg_qualtrics__survey') }}"
    question: "{{ ref('stg_qualtrics__question') }}"
    question_response: "{{ ref('stg_qualtrics__question_response') }}"
    question_option: "{{ ref('stg_qualtrics__question_option') }}"
    survey_response: "{{ ref('stg_qualtrics__survey_response') }}"
    sub_question: "{{ ref('stg_qualtrics__sub_question') }}"
    survey_version: "{{ ref('stg_qualtrics__survey_version') }}"
    survey_embedded_data: "{{ ref('stg_qualtrics__survey_embedded_data') }}"
    block: "{{ ref('stg_qualtrics__block') }}"
    block_question: "{{ ref('stg_qualtrics__block_question') }}"
    directory: "{{ ref('stg_qualtrics__directory') }}"
    directory_contact: "{{ ref('stg_qualtrics__directory_contact') }}"
    directory_mailing_list: "{{ ref('stg_qualtrics__directory_mailing_list') }}"
    contact_mailing_list_membership: "{{ ref('stg_qualtrics__contact_mailing_list_membership') }}"
    distribution: "{{ ref('stg_qualtrics__distribution') }}"
    distribution_contact: "{{ ref('stg_qualtrics__distribution_contact') }}"
    core_contact: "{{ ref('stg_qualtrics__core_contact') }}"
    core_mailing_list: "{{ ref('stg_qualtrics__core_mailing_list') }}"
