name: 'qualtrics_integration_tests'
version: '1.0.1'
profile: 'integration_tests'
config-version: 2

vars:
  qualtrics:
    qualtrics_schema: qualtrics_integration_tests
    # qualtrics__using_core_contacts: true # @docs-include
    # qualtrics__using_core_mailing_lists: true # @docs-include
    qualtrics_block_question_identifier: "block_question"
    qualtrics_block_identifier: "block"
    qualtrics_contact_mailing_list_membership_identifier: "contact_mailing_list_membership"
    qualtrics_core_contact_identifier: "core_contact"
    qualtrics_core_mailing_list_identifier: "core_mailing_list"
    qualtrics_directory_contact_identifier: "directory_contact"
    qualtrics_directory_mailing_list_identifier: "directory_mailing_list"
    qualtrics_directory_identifier: "directory"
    qualtrics_distribution_contact_identifier: "distribution_contact"
    qualtrics_distribution_identifier: "distribution"
    qualtrics_question_option_identifier: "question_option"
    qualtrics_question_response_identifier: "question_response"
    qualtrics_question_identifier: "question"
    qualtrics_sub_question_identifier: "sub_question"
    qualtrics_survey_embedded_data_identifier: "survey_embedded_data"
    qualtrics_survey_response_identifier: "survey_response"
    qualtrics_survey_version_identifier: "survey_version"
    qualtrics_survey_identifier: "survey"
    qualtrics_user_identifier: "user"
  
dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']

models:
  +schema: "qualtrics_{{ var('directed_schema','dev') }}"

seeds:
  +docs:
    show: False
  qualtrics_integration_tests:
    +column_types:
      _fivetran_synced: timestamp
      directory_unsubscribe_date: timestamp
      response_completed_at: timestamp
      last_accessed: timestamp
      account_creation_date: timestamp
      response_started_at: timestamp
      account_expiration_date: timestamp
      last_login_date: timestamp
      password_expiration_date: timestamp
      password_last_changed_date: timestamp
      unsubscribe_date: timestamp
    contact_mailing_list_membership:
      +column_types:
        unsubscribe_date: timestamp
    survey_response:
      +column_types:
        id: "{{ 'string' if target.type in ['bigquery','spark','databricks'] else 'varchar' }}"
        recorded_date: timestamp
        start_date: timestamp
    distribution:
      +column_types:
        survey_link_survey_id: "{{ 'string' if target.type in ['bigquery','spark','databricks'] else 'varchar' }}"
        id: "{{ 'string' if target.type in ['bigquery','spark','databricks'] else 'varchar' }}"
        parent_distribution_id: "{{ 'string' if target.type in ['bigquery','spark','databricks'] else 'varchar' }}"
    survey_version:
      +column_types:
        survey_id: "{{ 'string' if target.type in ['bigquery','spark','databricks'] else 'varchar' }}"
    block_question:
      +column_types:
        survey_id: "{{ 'string' if target.type in ['bigquery','spark','databricks'] else 'varchar' }}"
    question:
      +column_types:
        survey_id: "{{ 'string' if target.type in ['bigquery','spark','databricks'] else 'varchar' }}"
    question_option:
      +column_types:
        survey_id: "{{ 'string' if target.type in ['bigquery','spark','databricks'] else 'varchar' }}"
    survey:
      +column_types:
        id: "{{ 'string' if target.type in ['bigquery','spark','databricks'] else 'varchar' }}"
        creator_id: "{{ 'string' if target.type in ['bigquery','spark','databricks'] else 'varchar' }}"
    distribution_contact:
      +column_types:
        sent_at: timestamp
        opened_at: timestamp
        response_started_at: timestamp
        response_completed_at: timestamp
        response_id: "{{ 'string' if target.type in ['bigquery','spark','databricks'] else 'varchar' }}"
    directory_contact:
      +column_types:
        ext_ref: "{{ 'string' if target.type in ['bigquery','spark','databricks'] else 'varchar' }}"
        language: "{{ 'string' if target.type in ['bigquery','spark','databricks'] else 'varchar' }}"
        phone: "{{ 'string' if target.type in ['bigquery','spark','databricks'] else 'varchar' }}"
        directory_unsubscribe_date: timestamp
        creation_date: timestamp
    core_contact:
      +column_types:
        external_data_reference: "{{ 'string' if target.type in ['bigquery','spark','databricks'] else 'varchar' }}"
        language: "{{ 'string' if target.type in ['bigquery','spark','databricks'] else 'varchar' }}"
flags:
  send_anonymous_usage_stats: False
  use_colors: True
