name: 'qualtrics_integration_tests'
version: '0.1.0'
profile: 'integration_tests'
config-version: 2

vars:
  qualtrics_schema: qualtrics_integration_tests

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']

seeds:
  qualtrics_integration_tests:
    +column_types:
      _fivetran_synced: timestamp
    directory_contact:
      +column_types:
        ext_ref: "{{ 'string' if target.name in ['bigquery','spark','databricks'] else 'varchar' }}"
    core_contact:
      +column_types:
        external_data_reference: "{{ 'string' if target.name in ['bigquery','spark','databricks'] else 'varchar' }}"